### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by akeslo** [AlexxIT/PythonScriptsPro#10]
Is there any way to run scripts that use selenium? 

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import paho.mqtt.publish as publish
import json

```

# Web Options
options = webdriver.ChromeOptions()
options.headless = True
driver = webdriver.Chrome(
    executable_path=ChromeDriverManager().install(), options=options)
```

Error executing script: There is no such driver by url https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux32.zip

I'm using Selenium and Webdriver_Manager, getting the below error:

Thanks!

**Comment by AlexxIT** [comment]
Running scripts is not much different from running them directly through python
