### ISSUE TITLE
Cannot make it run

### ISSUE THREAD

**Issue by tukestolo** [AlexxIT/PythonScriptsPro#12]
![image](https://user-images.githubusercontent.com/61240309/185659839-c0e34543-fe07-48ce-a85e-60224c6b87fd.png)

script call

![image](https://user-images.githubusercontent.com/61240309/185659890-b7b52b21-5739-4452-a83d-21d2e8b8f948.png)

File

![image](https://user-images.githubusercontent.com/61240309/185659921-b4ac178d-ef27-4198-85f1-0a8269b477c1.png)

Can you help me please ?

**Comment by AlexxIT** [comment]
It is better to check the detailed description of the error in the logs. The answer will be there
