### ISSUE TITLE
Nothing do after executing your example scripts

### ISSUE THREAD

**Issue by martinmmi** [AlexxIT/PythonScriptsPro#15]
There is noting from your start_time example in the notifications. The ip example is also not working

![image](https://github.com/AlexxIT/PythonScriptsPro/assets/118231543/e11ceba9-bf75-400d-9629-6f104b7bc4b7)

**Comment by martinmmi** [comment]
![image](https://github.com/AlexxIT/PythonScriptsPro/assets/118231543/db0f470a-c4d1-4c9f-b2be-9f31838a3c5e)

**Comment by AlexxIT** [comment]
You're calling services completely wrong. How to do this is described in the Home Assistant documentation
