### ISSUE TITLE
Access to global scope from inside functions and loops

### ISSUE THREAD

**Issue by almazikv** [AlexxIT/PythonScriptsPro#18]
Hi,
I tried to run python script using this integration and have the following problem.
If i use functions i can not access global scope of variables and imported modules from within functions. 
I am getting following error: "name XXX is not defined"

For example:

```
import requests
import json 
def login():
    response = requests.post(api_url,data=json.dumps(todo), headers=headers)
```

results in error that "name 'requests' is not defined"

```
 def login():
       import requests
       import json 
       response = requests.post(api_url,data=json.dumps(todo), headers=headers)
```

works fine.

The same happens if i try to call a function from another function or from inside 'for' loop.
If i run my script using python3 it works fine.

**Comment by SpaceTeddy** [comment]
same here, 
no way to create good functions :(

**Comment by almazikv** [comment]
I think AlexxIT is not developing this project anymore. Try pyscript. Pyscript can also return values to HA.

**Comment by SpaceTeddy** [comment]
Is pyscript able to import custom libraries, or any library which is available by pip?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/PythonScriptsPro/releases/tag/v1.0.0
