### ISSUE TITLE
requesting the data return function in result_variable services

### ISSUE THREAD

**Issue by malinovsku** [AlexxIT/PythonScriptsPro#21]
in Core 2023.7, services have the ability to return data after execution, it would be cool if this component had such an opportunity.
PS now this is solved by running and waiting for the event in parallel and because of this complex constructions
https://developers.home-assistant.io/docs/dev_101_services/#supporting-response-data

**Comment by AlexxIT** [comment]
#16

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/PythonScriptsPro/releases/tag/v1.0.0
