### ISSUE TITLE
Don't get any response

### ISSUE THREAD

**Issue by collateral87** [AlexxIT/PythonScriptsPro#24]
Hi, thank you so much for adding this feature.

Unfortunatly i don't get response from my scripts.
I'm not sure if I'm doing something wrong or it's an issue.

![00](https://github.com/AlexxIT/PythonScriptsPro/assets/97076257/1bc10fa2-bb15-4171-9e3e-abdf9192cf92)

**Comment by malinovsku** [comment]
this problem also occurs, and in version 1.0.0, if there was an error in the script, there was an error in response_variable, in 1.0.1, response_variable is empty and only an error in the logs, even considering that an Exception is caught in the script

**Comment by collateral87** [comment]
should i use 1.0.0 until this is fixed?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/PythonScriptsPro/releases/tag/v1.0.2
