### ISSUE TITLE
def main()

### ISSUE THREAD

**Issue by SpaceTeddy** [AlexxIT/PythonScriptsPro#25]
Dear AlexxIT,
thanks a lot for your nice tool. I use it every day and works really good. After the last update it bring even more compatiblity to my python projects. So -> great! ;)

But may I ask a question about main().
is it possible to do something like this?...

```python
async def main():
   freaky_main_code = 1

if __name__ == "__main__":
    asyncio.run(main())
```

thanks a lot

**Comment by AlexxIT** [comment]
I don't understand what you want. `asyncio` or `__name__ == "__main__"`

**Comment by AlexxIT** [comment]
I think I can set `__name__` to `"__main__"`, but don't know if this is good idea.

**Comment by SpaceTeddy** [comment]
Anyhow, no problem. My scripts are running fine, and if this is possible, then it would be nice. If not, no worries 

cu
Chris
