### ISSUE TITLE
Unable to run py script.

### ISSUE THREAD

**Issue by ebolisa** [AlexxIT/PythonScriptsPro#4]
Hi, I'm new to this so I'd appreciate some help.

I'm trying to display my external ip (per your example) but I get the following in the log.
What should I do?

TIA

Unable to prepare setup for platform python_script.sensor: Unable to set up component.
8:58:08 PM – (ERROR) setup.py
Error during setup of component python_script
8:58:08 PM – (ERROR) pyscript (custom integration)
You are using a custom integration python_script which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
8:58:07 PM – (WARNING) loader.py

**Comment by AlexxIT** [comment]
pyscript - it's not mine integration
